name: Log latest release
on: push
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Send Coins By Github Id
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://localhost:3000/api/trpc/user.sendCoinsByGithubId?batch=1'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"0": {"json": {"user": {"id": "prueba","login": "korack2","name": "cual name","email": "admi2n@admin.com","avatarUrl": "url.com"},"coins": 123}}}'
